dist: trusty

sudo: required

language: scala

scala:
  - 2.12.3

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

script:
  - sbt test

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"
